export class AgentsMdAdapter {
  get name() { return 'agents-md'; }
  detect() { return true; }

  generate(knowledge, workflows, agents) {
    const lines = ['# AGENTS.md', '', '> Generated by UDA (Universal Dev AI)', ''];

    if (knowledge.conventions?.length > 0) {
      lines.push('## Coding Conventions');
      knowledge.conventions.forEach(c => lines.push(`- ${c}`));
      lines.push('');
    }

    if (knowledge.decisions?.length > 0) {
      lines.push('## Architecture');
      knowledge.decisions.forEach(d => lines.push(`- ${d}`));
      lines.push('');
    }

    return { 'AGENTS.md': lines.join('\n') };
  }
}
